update schema olh to v1.144.0
trendmicro/tm-v1-schema pull request #2
Opened 2024-11-12 08:59 UTC by trend-dennis-tseng

2024-11-29 08:14 UTC, rebeccalee828 requested changes

2024-11-29 08:14 UTC, rebeccalee828 commented on doc/Detections.yaml
>    Description_EN: The telemetry events match the Security Analytics Engine filter,
The telemetry events that match the Security Analytics Engine filter, and logonUsers stores the logonUsers value of the original events

2024-11-29 08:14 UTC, rebeccalee828 commented on doc/Detections.yaml
>    Description_EN: The host operating system name
The host OS name

2024-11-29 08:14 UTC, rebeccalee828 commented on doc/Cloud Activity Data.yaml
>    Description_EN: Additional data about the event that was not part of the request
The additional data about the event that was not part of the request

2024-11-29 08:14 UTC, rebeccalee828 commented on doc/Cloud Activity Data.yaml
>    Description_EN: Identifies the service event, including what triggered the event
The service event (including what triggered the event and the result)

2024-11-29 08:52 UTC, trend-dennis-tseng commented on doc/Cloud Activity Data.yaml
>    Description_EN: Additional data about the event that was not part of the request
We will update on this ticket: https://trendmicro.atlassian.net/browse/LUWA-19825

2024-11-29 08:52 UTC, trend-dennis-tseng commented on doc/Cloud Activity Data.yaml
>    Description_EN: Identifies the service event, including what triggered the event
We will update on this ticket: https://trendmicro.atlassian.net/browse/LUWA-19825

2024-11-29 08:52 UTC, trend-dennis-tseng commented on doc/Detections.yaml
>    Description_EN: The host operating system name
We will update on this ticket: https://trendmicro.atlassian.net/browse/LUWA-19825

2024-11-29 08:52 UTC, trend-dennis-tseng commented on doc/Detections.yaml
>    Description_EN: The telemetry events match the Security Analytics Engine filter,
We will update on this ticket: https://trendmicro.atlassian.net/browse/LUWA-19825

2024-11-29 08:59 UTC, rebeccalee828 approved these changes

2024-12-02 01:29 UTC, rebeccalee828 approved these changes

2024-12-02 01:30 UTC, merged