XDL update common schema to v1.135.0
trendmicro/tm-v1-schema pull request #46
Opened 2024-08-14 02:06 UTC by trend-dennis-tseng

2024-08-23 01:50 UTC, rebeccalee828 requested changes

2024-08-23 01:50 UTC, rebeccalee828 commented on doc/Detections.yaml
>    Description_EN: The endpoint host name or node where the event was detected
The endpoint hostname or node where the event was detected

2024-08-23 08:49 UTC, trend-dennis-tseng commented on doc/Detections.yaml
>    Description_EN: The endpoint host name or node where the event was detected
Update `Description_EN ` to : The endpoint hostname or node where the event was detected

2024-08-26 01:18 UTC, rebeccalee828 approved these changes

2024-09-18 03:18 UTC, rebeccalee828 approved these changes

2024-09-18 06:49 UTC, rebeccalee828 approved these changes

2024-09-18 06:51 UTC, trend-lucas-huang approved these changes
LGTM

2024-09-18 06:53 UTC, merged